source 'https://rubygems.org'

gem 'atomic'
gem 'bundler'
gem 'execjs'
gem 'jsmin'
gem 'json'
gem 'json-schema', '= 1.0.10'
gem 'rufus-lru'
gem 'mime-types'
gem 'minitest'
gem 'multi_json'
gem 'net-http-persistent'
gem 'puma'
gem 'rack'
gem 'rack-protection'
gem 'rack-test'
gem 'rspec'
gem 'rubyzip'
gem 'sinatra'
gem 'sinatra-assetpack'
